### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/cmsms#8]
Hi @mbardelmeijer 

Are you still interested in maintain this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by mbardelmeijer** [comment]
Hey @atymic, yeah sure! Will make some time available for a new release.

**Comment by mbardelmeijer** [comment]
@atymic are there any specific features that aren't working correctly on 5.5+?

Will update the package in general and add support for Laravel 6.0 but just curious if you were running into any issues at the moment.

**Comment by atymic** [comment]
I assume everything will work properly (there haven't been any major changes to the notification system).

I'm just going through all the channels and making sure everything is up to date :)

https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/issues/18

**Comment by atymic** [comment]
PR to add it to the website as well here:
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/pull/23

Thanks for updating :)
